--ДНЕВНИК ВКАТУНА


TRUNCATE TABLE student RESTART IDENTITY CASCADE;
TRUNCATE TABLE faculty RESTART IDENTITY CASCADE;
TRUNCATE TABLE avatar RESTART IDENTITY CASCADE;


ALTER TABLE student
    ALTER COLUMN id SET DATA TYPE INTEGER;
ALTER SEQUENCE student_id_seq RESTART WITH 1;

ALTER TABLE faculty
    ALTER COLUMN id SET DATA TYPE INTEGER;
CREATE SEQUENCE faculty_id_seq START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE faculty_id_seq RESTART WITH 1;


ALTER TABLE avatar
    ALTER COLUMN id SET DATA TYPE INTEGER;
CREATE SEQUENCE avatar_id_seq START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE avatar_id_seq RESTART WITH 1;
